version: '3.8'

services:
  app:
    container_name: estimate-restock
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./api.py:/app/api.py
      - ./main.py:/app/main.py
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: admin
      MONGO_PORT: 27017
      MONGO_HOST: mongo
    networks:
      - server

  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - gui
      - server
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
    networks:
      - gui

volumes:
  mongodb_data:
    driver: local

networks:
  server:
    name: server
  gui:
    name: gui
